version: '3'
services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - xpack.security.enabled=false # 보안 비활성화
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data
  #   networks:
  #     - elk

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.15.0
  #   container_name: logstash
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - "5044:5044"
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline
  #   networks:
  #     - elk

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.15.0
  #   container_name: kibana
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - xpack.security.enabled=false # 보안 비활성화
  #   networks:
  #     - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: filebeat
    user: root
    volumes:
      - ../logs:/var/log/logs:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: >
      sh -c "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat -e -c /usr/share/filebeat/filebeat.yml -d '*'"
    #   -E filebeat.inputs.0.type=log
    #   -E filebeat.inputs.0.enabled=true
    #   -E filebeat.inputs.0.paths=["/var/log/logs/*.log"]
    #   -E output.logstash.hosts=["logstash:5044"]
    depends_on:
      - logstash
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch-data: